//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.Componens
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int DishId { get; set; }
        public int IngredirntId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Description { get; set; }
        public int CoolondStageId { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
